version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github-pages
    versions:
    - "210"
    - "212"
    - "213"
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: activesupport
    versions:
    - 6.0.3.4
