# Site settings
title: Keep a moment
email: your-email@domain.com
description: "“If you see something that moves you, and then snap it, you keep a moment.” (Linda McCartney)"
baseurl: ""
url: "http://www.keepamoment.com"

# Build settings
markdown: kramdown
permalink: /:title